name: 🔍️ PR Title Validation
description: "This action will validate the title of a PR, ensuring it follows the expected naming rules."

runs:
    using: "composite"
    steps:
        - name: Validate that PR title follows Conventional Commit format
          shell: bash
          run: |
              ALLOWED_PREFIXES="feat|fix|chore|refactor|docs|style|test|perf|ci|build"
              PR_TITLE="${{ github.event.pull_request.title }}"

              echo "PR Title: $PR_TITLE"

              if [[ ! $PR_TITLE =~ ^($ALLOWED_PREFIXES)(\(.+\))?!?:.*$ ]]; then
                echo "The PR title is invalid: $PR_TITLE"
                echo "It must follow the conventional commit format." 
                exit 1
              fi

              echo "The PR title follows the Conventional Commit format."
