name: "Deploy to Fusion Portal"
author: "Arne Kristian Jansen"
description: "This action will deploy to the Fusion Portal, using the provided SP and Fusion environment"
inputs:
    fusion-portal-url:
        description: "Url to the endpoint for deployment and publishing."
        required: true
    app-key:
        description: "The AppKey, as used in the Fusion Portal, of the application."
        required: true
    artifact-path:
        description: "The path and name of the artifact that should be uploaded to the Fusion Portal."
        required: true
    publish:
        description: "Optional - determines if the deployed artifact should immediately be published or not. Default true."
        required: false
        default: true
    azure-tenant-id:
        description: "Id of the Azure tenant."
        required: true
    azure-client-id:
        description: "Id of the Service Principal in Azure."
        required: true
    azure-resource-id:
        description: "Id of the resource group for deployment."
        required: true

runs:
    using: "composite"
    steps:
        - name: "Login to Azure"
          uses: azure/login@v1
          with:
              client-id: ${{ inputs.azure-client-id }}
              tenant-id: ${{ inputs.azure-tenant-id }}
              allow-no-subscriptions: true

        - name: "Obtain token for upload"
          shell: bash
          run: echo "FUSION_TOKEN=$(az account get-access-token --resource '${{ inputs.azure-resource-id }}' | jq '.accessToken')" >> $GITHUB_ENV

        - name: "Upload to Fusion Portal"
          shell: bash
          run: |
              curl -X POST \
              -i \
              -f \
              -H "Content-Type: application/zip" \
              -H "Authorization: Bearer ${{ env.FUSION_TOKEN }}" \
              --data-binary @${{ inputs.artifact-path }} \
              "${{ inputs.fusion-portal-url }}/api/apps/${{ inputs.app-key }}/versions"

        - name: "Publish in Fusion Portal"
          shell: bash
          run: |
              if ${{ inputs.publish == true }} == 'true'; then
                curl -X POST \
                -i \
                -f \
                -H "Content-Length: 0" \
                -H "Authorization: Bearer ${{ env.FUSION_TOKEN }}" \
                "${{ inputs.fusion-portal-url }}/api/apps/${{ inputs.app-key }}/publish"
              else
                echo "Publish is set to false, not publishing."        
              fi
