version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      commit-message:
          prefix: "ci(actions)"
      schedule:
          interval: "daily"
      reviewers:
          - "equinor/farfetch-d"
