name: "Commit and push changes with signed commit"
description: "This action commits and pushes changes to a specified file with a signed commit message. The caller needs to set the following environment variables: FILE_TO_COMMIT, COMMIT_MESSAGE, and REPO."
inputs:
    branch:
        description: "The name of the branch to commit the file to."
        type: string
        required: true

runs:
    using: "composite"
    steps:
        - name: Commit and push if changes
          shell: bash
          env:
              GH_TOKEN: ${{ github.token }}
              BRANCH: ${{inputs.branch}}
          run: |
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "Farfetch'd Actions Bot"
              git add "$FILE_TO_COMMIT"
              if git diff --staged --quiet; then
                echo "No changes to commit"
              else
                export SHA=$(git rev-parse HEAD:$FILE_TO_COMMIT)
                export CONTENT=$(base64 -i $FILE_TO_COMMIT)
                gh api --method PUT "/repos/$REPO/contents/$FILE_TO_COMMIT" \
                  --field message="$COMMIT_MESSAGE" \
                  --field content="$CONTENT" \
                  --field encoding="base64" \
                  --field branch="$BRANCH" \
                  --field sha="$SHA"
                fi
